name: SSPanel_Auto_Checkin

on:
    workflow_dispatch:
    push:
        branches:
            - master
    schedule:
        - cron: '20 18 * * *'
    watch:
        types: 
            - started

env:
    TZ: Asia/Shanghai
    USERS: https://going.91merry.xyz/----2646608706@qq.com----ejJHFG67756449jHjahd;https://feisucloud.pw----2646608706@qq.com----jhSgF564bDXvh5632;https://888888.sbs/user----2646608706@qq.com----hgDfXf55687bZDG56;https://cwv587.com----2646608706@qq.com----9jH55kHjbH65;




    PUSH_KEY: SCT133120TqdSjM1srvhwMvUJp0xkifOpi
    PUSH_TURBO_KEY: ${{secrets.PUSH_TURBO_KEY}}
    QMSG_KEY: ${{secrets.QMSG_KEY}}
    DDBOT_TOKEN: ${{secrets.DDBOT_TOKEN}} 
    TELEGRAMBOT_TOKEN: ${{secrets.TELEGRAMBOT_TOKEN}} 
    TELEGRAMBOT_CHATID: ${{secrets.TELEGRAMBOT_CHATID}}
    PUSHPLUS_TOKEN: ${{secrets.PUSHPLUS_TOKEN}}
    WEWORK_ID: ${{secrets.WEWORK_ID}}
    WEWORK_AGENT_ID: ${{secrets.WEWORK_AGENT_ID}}
    WEWORK_SECRET: ${{secrets.WEWORK_SECRET}}
    DISPLAY_CONTEXT: ${{secrets.DISPLAY_CONTEXT}}

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout codes
              uses: actions/checkout@v2
            
            - name: Install depends
              run: |
                sudo apt-get update
                sudo apt-get -y install curl jq

            - name: Request API
              run: |
                bash ssp-autocheckin.sh
